name:                netmon
version:             0.1.0.0
github:              "smalewski/netmon"
license:             BSD3
author:              "Stefan Malewski"
maintainer:          "alviprofluvium@gmail.com"
copyright:           "2018 Stefan Malewski"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            TUI Bandwidth Monitor
category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/smalewski/netmon#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  netmon-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - netmon

tests:
  netmon-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - netmon
